apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellbing-client-deployment
  namespace: hoyaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wellbing-client
  template:
    metadata:
      labels:
        app: wellbing-client
    spec:
      containers:
        - name: wellbing-client
          image: parkjeongho/wellbing-client:38a8f87d325868a1554c5d9495fdebae858e27c3
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wellbing-client-service
  namespace: hoyaweb
spec:
  selector:
    app: wellbing-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
