apiVersion: apps/v1
kind: Deployment
metadata:
  name: wellbing-server-deployment
  namespace: hoyaweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wellbing-server
  template:
    metadata:
      labels:
        app: wellbing-server
    spec:
      containers:
        - name: wellbing-server
          image: parkjeongho/wellbing-server:38a8f87d325868a1554c5d9495fdebae858e27c3
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: wellbing-data-storage
              mountPath: /usr/src/app/data
            - name: wellbing-data-storage
              mountPath: /usr/src/app/public/uploads
      volumes:
        - name: wellbing-data-storage
          persistentVolumeClaim:
            claimName: wellbing-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: wellbing-server-service
  namespace: hoyaweb
spec:
  selector:
    app: wellbing-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
